# Site settings
title: "Je'aime Powell"
email: jeaimehp@gmail.com
url: https://jeaimehp.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: jeaimehp.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jeaimehpc
  - title: github
    url: https://github.com/jeaimehp

# Build settings
markdown: kramdown
permalink: pretty
